### ISSUE TITLE
Where's the website repo?

### ISSUE THREAD

**Issue by devinhalladay** [GD399-OSD/OSD-book#2]
Hey @bjornmeansbear any chance you still have a local copy of the repo for our bindery website? I could've sworn it was on github, but I can't find it anywhere.

**Comment by devinhalladay** [comment]
JK I was actually looking for the GD213–SGD site. The repo is here https://github.com/gd314-sgd/publication

**Comment by bjornmeansbear** [comment]
I can't believe that was 2019 already... oh man. Good times working on that thing!
